name: Docker build and push

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
    RUST_VERSION: '1.85.1'

    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/emtk

    build-docker:
      name: build-docker
      runs-on: ubuntu-24.04
      steps:
        - name: Checkout sources
          uses: actions/checkout@v4
        - name: Dockerhub login
          run: |
            echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v3
        - name: Setup Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            platforms: linux/amd64,linux/arm64
            push: true
            tags: |
              ${{ env.IMAGE_NAME }}
            build-args: |
              RUST_VERSION=${{ env.RUST_VERSION }}

